src/Entity/Tareas.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\TareasRepository")
 */
class Tareas
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=500)
     */
    private $nombre;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $descripcion;

    /**
     * @ORM\Column(type="integer", length=11, nullable=true)
     */
    private $id_usuario;

    /**
     * @ORM\Column(type="string", length=500, nullable=true)
     */
    private $fecha_creacion;

    /**
     * @ORM\Column(type="integer", length=11)
     */
    private $id_estado;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->nombre;
    }

    public function setNombre(string $nombre): self
    {
        $this->nombre = $nombre;

        return $this;
    }

    public function getDescripcion(): ?string
    {
        return $this->descripcion;
    }

    public function setDescripcion(?string $descripcion): self
    {
        $this->descripcion = $descripcion;

        return $this;
    }

    public function getIdUsuario(): ?string
    {
        return $this->id_usuario;
    }

    public function setIdUsuario(?string $id_usuario): self
    {
        $this->id_usuario = $id_usuario;

        return $this;
    }

    public function getFechaCreacion(): ?string
    {
        return $this->fecha_creacion;
    }

    public function setFechaCreacion(?string $fecha_creacion): self
    {
        $this->fecha_creacion = $fecha_creacion;

        return $this;
    }

    public function getIdEstado(): ?string
    {
        return $this->id_estado;
    }

    public function setIdEstado(?string $id_estado): self
    {
        $this->id_estado = $id_estado;

        return $this;
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8"> 
        <!-- Bootstrap CSS -->
        
        <link href="{{ asset ('css/bootstrap.css') }}" rel="stylesheet" >
        <link href="{{ asset ('estilo.css') }}" rel="stylesheet" >
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

        <title>{% block title %}PRUEBA TÉCNICA{% endblock %}</title>
        {% block stylesheets %}
        
        {% endblock %}
    </head>
    <body> 
        <div class="menu text-center">

            <h2 class="mt-2">PRUEBA TÉCNICA </h2>
            
            
            <a class="menu_item" href="{{'/'}}"> INICIO</a>
            <a class="menu_item" href="{{'/login'}}"> LOGIN</a>
                <a class="menu_item" href="{{'/usuarios'}}"> USUARIOS</a>
                <a class="menu_item" href="{{'/estados'}}"> ESTADOS</a>
                <a class="menu_item" href="{{'/tareas'}}"> TAREAS</a>
                {% if app.session.get('usuario') %}
                Bienvenido {{app.session.get('usuario')}}
                <a class="menu_item" href="{{'/logout'}}"> LOGOUT</a>
                {% endif %}
            </div>
        {% block body %}{% endblock %}
        {% block javascripts %}
       
        {% endblock %}
    </div>
    </body>
</html>

templates/editestado.html.twig
 {% extends 'base.html.twig'%}

 {% block stylesheets %}
 {{parent()}}
 {% endblock %}
 

 {% block body %} 

 <h2 class="title">EDITAR ESTADO</h2>
 
 <form class="formstatus" action="{{  path('editarestado', {'id' : estado.id }) }}">
     <label class="field" for="nombre">Estado: </label>
     <input class="field" type="text" name="nombre" id="nombre" value ="{{estado.nombre}}">
     <label class="field" for="descripcion">Descripción: </label>
     <textarea class="field" name="descripcion" id="descripcion">
         {{estado.descripcion}}
     </textarea> 
     
     <a href="{{'/estados'}}"><input type="button" name="cancell" value="<- Volver "></a>
     <input type="submit" name="edit" value="Editar tarea">
 </form>

 <a href="{{ '/' }}"><button class="mt-5">Ir a inicio</button></a>       

 {% endblock %}
 {% block javascripts %}

 {% endblock %}

templates/edittarea.html.twig
 {% extends 'base.html.twig'%}

 {% block stylesheets %}
 {{parent()}}
 {% endblock %}
 

 {% block body %} 

 <h2 class="title">EDITAR TAREA</h2>
 
 <form class="formstatus" action="{{  path('editartarea', {'id' : tarea.id }) }}">
     <label class="field" for="nombre">Tarea: </label>
     <input class="field" type="text" disabled name="nombre" id="nombre" value ="{{tarea.nombre}}">
     <label class="field" for="fecha">Fecha de creación: </label>
     <input class="field" type="text" disabled name="fecha" id="fecha" value ="{{tarea.fechaCreacion}}">
     <label class="field" for="descripcion">Descripción: </label>
     <textarea class="field" name="descripcion" id="descripcion" disabled>
         {{tarea.descripcion}}
     </textarea> 
     <label class="field" for="usuario">Usuario Asignado:
        {% for usuario in usuarios %}
            {% if (tarea.idUsuario == usuario.id)  %}
                {{ usuario.usuario}}
            {% endif %}
        {% endfor %}
     </label>
     <select class="field" name="usuario">
         {% for usuario in usuarios %}
            {% if (tarea.idUsuario == usuario.id)  %}
            {{ usuario.usuario}}
            {% endif %}
            <option value="{{usuario.id}}"> {{usuario.usuario}}</option>
        {% endfor %}
     </select>
     
     <label class="field" for="usuario">Estado actual de la tarea:
        {% for estado in estados %}
            {% if (tarea.idEstado == estado.id)  %}
                {{ estado.nombre}}
            {% endif %}
        {% endfor %}
     </label>
     <select class="field" name="estado">
         {% for estado in estados %}
            {% if (tarea.idEstado == estado.id)  %}
            {{ estado.nombre}}
            {% endif %}
            <option value="{{estado.id}}"> {{estado.nombre}}</option>
        {% endfor %}
     </select>
     <a href="{{'/tareas'}}"><input type="button" name="cancell" value="<- Volver "></a>
     <input type="submit" name="edit" value="Editar tarea">
 </form>

 <a href="{{ '/' }}"><button class="mt-5">Ir a inicio</button></a>       

 {% endblock %}
 {% block javascripts %}

 {% endblock %}

templates/estados.html.twig
 {% extends 'base.html.twig'%}

        {% block stylesheets %}
        {{parent()}}
        {% endblock %}
        

        {% block body %} 

        <h2 class="title">ESTADOS DE LAS TAREAS</h2>
        
        
        <table class="table" >
            <thead>
                <th>Estado</th>
                <th>Descripción</th> 
                <th> </th>
            </thead>
            
            <tbody>
                {% for estado in estados %}
            <tr>
                <td> {{ estado.nombre }}</td>
                <td> {{ estado.descripcion }}</td>
               
                
                {% if app.session.get('usuario') %}
                <td>
                    <a href="{{ path('editestado', {'id' : estado.id }) }}"><button>Editar</button></a>
                </td>
                {% endif %}
            </tr>
                {% endfor %}
            </tbody>
        </table>
                
        <a href="{{ '/form_estado' }}"><button class="mt-5">Añadir nuevo estado </button></a>
        <a href="{{ '/' }}"><button class="mt-5">Ir a inicio</button></a>       
        {% endblock %}
        {% block javascripts %}
       
        {% endblock %}
  

templates/form_edituser.html.twig
 {% extends 'base.html.twig'%}

 {% block stylesheets %}
 {{parent()}}
 {% endblock %}
 

 {% block body %} 

 <h2 class="title">EDITAR USUARIO</h2>
 
 <form class="formuser" action="{{path('editarusuario', {'id' : usuario.id })}}">
     <label class="field" for="name">Nombre: </label>
     <input class="field" type="text" name="nombre" id="nombre" value="{{usuario.nombre}}">
     <label class="field" for="apellido">Apellido: </label>
     <input class="field" type="text" name="apellido" id="apellido" value="{{usuario.apellido}}"> 
     <label class="field" for="email">Email: </label>
     <input class="field" type="text" name="email" id="email" value="{{usuario.email}}"> 
     <label class="field" for="pass">Contraseña: </label>
     <input class="field" type="password" name="pass" id="pass" value="{{usuario.pass}}"> 
     <label class="field" for="direccion">Dirección: </label>
     <input class="field" type="text" name="direccion" id="direccion" value="{{usuario.direccion}}"> 
     <label class="field" for="habilitado">Usuario habilitado: </label>
      {% if usuario.estado == 'Admin' %} 
      <p> Este usuario no se puede desactivar. Es el administrador del sitio.</p>
      {% else %}
        {% if usuario.estado == 'habilitado' %}
           <input class="field" type="checkbox" name="desabilitado" checked value="desabilitado">
        {% else %}
        <input class="field" type="checkbox" name="habilitado" value="habilitado">
        {% endif %}
    {% endif %}
     <input type="submit" name="add_user">
 </form>
 
 <a href="{{ '/' }}"><button class="mt-5">Ir a inicio</button></a>       

 {% endblock %}
 {% block javascripts %}

 {% endblock %}

templates/inicio.html.twig
 {% extends 'base.html.twig'%}

 {% block stylesheets %}
 {{parent()}}
 {% endblock %}
 

 {% block body %} 

 <h2 class="title">INICIO</h2>

 <div class="text-center">
 <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s. 
<p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s</p>
         </div>
 {% endblock %}
 {% block javascripts %}

 {% endblock %}

templates/login.html.twig
 {% extends 'base.html.twig'%}

 {% block stylesheets %}
 {{parent()}}
 {% endblock %}
 

 {% block body %} 

 <h2 class="title">LOGIN</h2>

 <form class=" tabla formstatus" action="{{'/login_usuario'}}">
    <label class="field" for="usuario">Usuario: </label>
    <input class="field" type="text" name="usuario" id="usuario">
    <label class="field" for="pass">Password: </label>
    <input class="field" type="password" name="pass" id="pass">
    
    <input class="menu_item mt-4" type="submit" name="login">
</form>

         
 {% endblock %}
 {% block javascripts %}

 {% endblock %}

templates/nuevatarea.html.twig
 {% extends 'base.html.twig'%}

 {% block stylesheets %}
 {{parent()}}
 {% endblock %}
 

 {% block body %} 

 <h2 class="title">NUEVA TAREA</h2>
 
 <form class="formstatus" action="{{'/nuevatarea'}}">
     <label class="field" for="name" >Nombre: *</label>
     <input class="field" type="text" name="name" id="name" required>
     <label class="field" for="description">Descripción: </label>
     <input class="field" type="text" name="description" id="descripcion"> 
     <label class="field" for="userid"  >Usuario encargado: </label>
        <select  name="userid" class="field" >
            {% for usuario in usuarios %}
            <option  value="{{usuario.id}}"> {{ usuario.nombre }} {{ usuario.apellido }} </option>
            {% endfor %}
        </select>
       <label class="field" for="statusid">Estado de la tarea: </label>
       <input class="field" type="text" disabled name="statusid" value="Pendiente">
     
     <input type="submit" name="add_status">
 </form>
 
 <a href="{{ '/' }}"><button class="mt-5">Ir a inicio</button></a>       

 {% endblock %}
 {% block javascripts %}

 {% endblock %}

templates/nuevoestado.html.twig
 {% extends 'base.html.twig'%}

 {% block stylesheets %}
 {{parent()}}
 {% endblock %}
 

 {% block body %} 

 <h2 class="title">NUEVO ESTADO</h2>
 
 <form class="formstatus" action="{{'/nuevoestado'}}">
     <label class="field" for="name">Estado: </label>
     <input class="field" type="text" name="name" id="name">
     <label class="field" for="description">Descripción: </label>
     <textarea class="field" name="description" id="description"></textarea> 
     
     <input type="submit" name="add_status">
 </form>

 <a href="{{ '/' }}"><button class="mt-5">Ir a inicio</button></a>       

 {% endblock %}
 {% block javascripts %}

 {% endblock %}

templates/nuevousuario.html.twig
 {% extends 'base.html.twig'%}

 {% block stylesheets %}
 {{parent()}}
 {% endblock %}
 

 {% block body %} 

 <h2 class="title">NUEVO USUARIO</h2>
 
 <form class="formuser" action="{{'/nuevousuario'}}">
     <label class="field" for="name">Nombre: </label>
     <input class="field" type="text" name="name" id="name">
     <label class="field" for="subname">Apellido: </label>
     <input class="field" type="text" name="subname" id="subname"> 
     <label class="field" for="email">Email: </label>
     <input class="field" type="text" name="email" id="email"> 
     <label class="field" for="pass">Contraseña: </label>
     <input class="field" type="password" name="pass" id="pass"> 
     <label class="field" for="address">Dirección: </label>
     <input class="field" type="text" name="address" id="address"> 
     
     <input type="submit" name="add_user">
 </form>
 
 <a href="{{ '/' }}"><button class="mt-5">Ir a inicio</button></a>       

 {% endblock %}
 {% block javascripts %}

 {% endblock %}

templates/tareas.html.twig
 {% extends 'base.html.twig'%}

 {% block stylesheets %}
 {{parent()}}
 {% endblock %}
 

 {% block body %} 

 <h2 class="title">LISTADO DE TAREAS</h2>
 
 
 <form action="{{'/buscartareas'}}" name="buscar">
    <label for="buscar">Buscar tarea por nombre: </label>
     <input class="mb-2 buscar" type="text" name="buscar" placeholder="Buscar tarea..."> 
     <input type="submit" value="Buscar">

 </form>
     <a href="{{'/tareas'}}"><button>Ver todas</button></a>
     
 <table class="table">
     <thead class="table_title">
         <th>Nombre</th>
         <th> Descripción</th>
         <th> Fecha </th>
         <th> Estado</th>
         <th > Usuario</th>
         <th > </th>
     </thead>
     
     <tbody>
         {% for tarea in tareas %}
         <tr>
         <td > {{ tarea.nombre }}</td>
        <td> {{ tarea.descripcion }}</td>     
         <td>  {{tarea.fechaCreacion }} </td>
         {% for estado in estados %} 
            {% if (tarea.idEstado == estado.id)  %}
                <td> {{estado.nombre}} </td>
            {% endif %}
         {% endfor %}   
         {% for usuario in usuarios %} 
            {% if (tarea.idUsuario == usuario.id)  %}
                <td> {{usuario.usuario}} {{ usuario.nombre }} {{ usuario.apellido }}</td>
            {% endif %}
         {% endfor %}<td>
             
        {% if app.session.get('usuario') %}
         <a href="{{ path('edittarea', {'id' : tarea.id }) }}"><button>Editar</button></a></td>
         {% endif %}
         </tr>
         {% endfor %} 
     </tbody>
      </table>
         <a href="{{'/form_tareas'}}"><button class="mt-5">Nueva tarea</button></a>
         <a href="{{ '/' }}"><button class="mt-5">Ir a inicio</button></a>       

 {% endblock %}
 {% block javascripts %}

 {% endblock %}

templates/usuarios.html.twig
 {% extends 'base.html.twig'%}

 {% block stylesheets %}
 {{parent()}}
 {% endblock %}
 

 {% block body %} 
 
 <h2 class="title">LISTADO DE USUARIOS</h2>
 {% if app.session.get('usuario') %}

     
 <form action="{{'/buscarusuario'}}" name="buscar">
    <label for="buscar">Buscar usuario por nombre: </label>
     <input class="mb-2 buscar" type="text" name="buscar" placeholder="Buscar usuario..."> 
     <input type="submit" value="Buscar">
 </form>
     <a href="{{'/usuarios'}}"><button>Ver todos</button></a>

 <table class="table">
     
     <thead class="table_title">
         <th> Usuario </th>
         <th colspan="2">Nombre</th>
         <th> Email</th>
         <th> Dirección</th>

         <th colspan="2"> </th>
     </thead>
     
     <tbody>
         {% for usuario in usuarios %}
         
         <tr>
             <td> {{usuario.usuario}}</td>
         <td colspan="2"> {{ usuario.nombre }}
              {{ usuario.apellido }}</td>
        <td> {{ usuario.email }}</td>     
         <td> {{ usuario.direccion }}</td>
            
         <td> {{ usuario.estado }}</td>
         <td>
         <a href="{{ path('form_edituser', {'id' : usuario.id }) }}"><button>Editar</button></a>
        </td>
         
         </tr>
         {% endfor %}
     </tbody>
      </table>
         <a href="{{'/form_usuario'}}"><button class="mt-5">Nuevo usuario</button></a>
         <a href="{{ '/' }}"><button class="mt-5">Ir a inicio</button></a>       

         
 {% else %}
 <div class="text-center">
     
 <p> PARA VER LOS USUARIOS DE LA APLICACIÓN ES NECESARIO INICIAR SESIÓN</p>
 <a href="{{ '/' }}"><button class="mt-5">Ir a inicio</button></a>
 <a href="{{ '/login' }}"><button class="mt-5">LOGIN</button></a>

 </div>
 {% endif %}



 {% endblock %}
 {% block javascripts %}

 {% endblock %}